import path from 'node:path';
import type { AdapterContext, AdapterPlan, FrameworkAdapter } from '../types.js';
import { createFileChange, ensureEnvLineChange, ensureGitignoreChange, fileExists } from '../util.js';

/**
 * Node/Express framework adapter.
 * Injects a lib/ai helper + env wiring for a plain Node/Express app.
 */
export const expressAdapter: FrameworkAdapter = {
  id: 'node-express',
  async detect(ctx: AdapterContext): Promise<boolean> {
    const pkg = path.join(ctx.cwd, 'package.json');
    return fileExists(pkg) && /"express"\s*:/.test(await safeRead(pkg));
  },
  async plan(ctx: AdapterContext): Promise<AdapterPlan> {
    const changes = [];

    const helper = path.join(ctx.cwd, 'lib', 'ai.js');
    const helperChange = await createFileChange(
      helper,
      `// Auto-generated by localbrain. Free, private, local AI client.\nexport { ai } from 'localbrain-client'\n`,
      'Add lib/ai.js helper',
    );
    if (helperChange) changes.push(helperChange);

    const envChange = await ensureEnvLineChange(
      path.join(ctx.cwd, '.env'),
      'LOCALBRAIN_URL',
      ctx.endpointUrl,
      'Set LOCALBRAIN_URL in .env',
    );
    if (envChange) changes.push(envChange);

    const gitignore = await ensureGitignoreChange(ctx.cwd, '.env');
    if (gitignore) changes.push(gitignore);

    return {
      changes,
      warnings: [],
      manualInstructions:
        `Use it in a route:\n  import { ai } from './lib/ai.js'\n  app.post('/extract', async (req,res) => res.json(await ai.extract(req.body.text, { name:'', amount:0 })))`,
    };
  },
};

async function safeRead(p: string): Promise<string> {
  try {
    return await (await import('node:fs/promises')).readFile(p, 'utf8');
  } catch {
    return '';
  }
}
