import path from 'node:path';
import type { AdapterContext, AdapterPlan, FrameworkAdapter } from '../types.js';
import { createFileChange, ensureEnvLineChange, ensureGitignoreChange, fileExists } from '../util.js';

/**
 * Next.js framework adapter.
 * Injects a lib/ai client helper + env wiring (LOCALBRAIN_URL in .env.local,
 * added to .gitignore). Shown as a diff; skippable with --config-only.
 */
export const nextjsAdapter: FrameworkAdapter = {
  id: 'nextjs',
  async detect(ctx: AdapterContext): Promise<boolean> {
    const pkg = path.join(ctx.cwd, 'package.json');
    return (
      fileExists(path.join(ctx.cwd, 'next.config.js')) ||
      fileExists(path.join(ctx.cwd, 'next.config.mjs')) ||
      fileExists(path.join(ctx.cwd, 'next.config.ts')) ||
      (fileExists(pkg) && /"next"\s*:/.test(await safeRead(pkg)))
    );
  },
  async plan(ctx: AdapterContext): Promise<AdapterPlan> {
    const changes = [];
    const warnings: string[] = [];

    const helper = path.join(ctx.cwd, 'lib', 'ai.ts');
    const helperChange = await createFileChange(
      helper,
      `// Auto-generated by localbrain. Free, private, local AI client.\nexport { ai } from 'localbrain'\n`,
      'Add lib/ai.ts helper',
    );
    if (helperChange) changes.push(helperChange);

    const envChange = await ensureEnvLineChange(
      path.join(ctx.cwd, '.env.local'),
      'LOCALBRAIN_URL',
      ctx.endpointUrl,
      'Set LOCALBRAIN_URL in .env.local',
    );
    if (envChange) changes.push(envChange);

    const gitignore = await ensureGitignoreChange(ctx.cwd, '.env.local');
    if (gitignore) changes.push(gitignore);

    warnings.push(
      'Next.js on serverless (Vercel/Netlify) cannot run a local model in production — use it in dev, or run the model on a server/sidecar. See README "The honest part about free".',
    );

    return {
      changes,
      warnings,
      manualInstructions:
        `Use it in a route:\n  import { ai } from '@/lib/ai'\n  const label = await ai.classify(text, ['a','b'])`,
    };
  },
};

async function safeRead(p: string): Promise<string> {
  try {
    return await (await import('node:fs/promises')).readFile(p, 'utf8');
  } catch {
    return '';
  }
}
